In [1]:
'''Use NumPy program to generate an array of 15 random numbers 
from a standard normal distribution

In [54]:
import numpy as np
rand_num = np.random.normal(0,1,15)
rand_num

array([ 0.67310688, -0.98729849, -0.86481285, -0.52446696, -0.84516991,
        0.72264999, -0.28328711,  1.43115071, -0.06304956,  0.33976206,
        1.02277409, -0.7772153 , -2.03978177,  3.54273827,  2.37727145])

In [52]:
'''Create an array of 20 linearly spaced points between 0 and 1

In [53]:
np.linspace(0, 1, 20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [ ]:
'''declare a numpy array of values from 1 to 100 and make it into a 10*10 matrix

In [55]:
import numpy as np
array = np.arange(100).reshape(10,10)
array

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [ ]:
'''using the previously defined matrix print rows 1,5,6

In [56]:
print(array[0])
print(array[4])
print(array[5])

[0 1 2 3 4 5 6 7 8 9]
[40 41 42 43 44 45 46 47 48 49]
[50 51 52 53 54 55 56 57 58 59]


In [ ]:
'''using the same matrix print values from 3rd row 2nd column to 5th row 8th column

In [57]:
print(array[2:5,1:8])

[[21 22 23 24 25 26 27]
 [31 32 33 34 35 36 37]
 [41 42 43 44 45 46 47]]


In [ ]:
'''Write a code to generate a 1000 random numbers each in the range(0,1)
such that the count of all random points like are almost same

In [58]:
from random import seed
from random import random
seed(1)
for _ in range(1000):
    value = random()
    print(value)

0.13436424411240122
0.8474337369372327
0.763774618976614
0.2550690257394217
0.49543508709194095
0.4494910647887381
0.651592972722763
0.7887233511355132
0.0938595867742349
0.02834747652200631
0.8357651039198697
0.43276706790505337
0.762280082457942
0.0021060533511106927
0.4453871940548014
0.7215400323407826
0.22876222127045265
0.9452706955539223
0.9014274576114836
0.030589983033553536
0.0254458609934608
0.5414124727934966
0.9391491627785106
0.38120423768821243
0.21659939713061338
0.4221165755827173
0.029040787574867943
0.22169166627303505
0.43788759365057206
0.49581224138185065
0.23308445025757263
0.2308665415409843
0.2187810373376886
0.4596034657377336
0.28978161459048557
0.021489705265908876
0.8375779756625729
0.5564543226524334
0.6422943629324456
0.1859062658947177
0.9925434121760651
0.8599465287952899
0.12088995980580641
0.3326951853601291
0.7214844075832684
0.7111917696952796
0.9364405867994596
0.4221069999614152
0.830035693274327
0.670305566414071
0.3033685109329176
0.587580606143

In [ ]:
'''Write the commands to get standard deviation, mean, mode, median for a given vector

In [59]:
import numpy as np
from scipy import stats
array=[110,12,140,34,56,78,69,20,34]
print(np.std(array))
print(np.mean(array))
print(np.median(array))
print(stats.mode(array))

40.21915273739093
61.44444444444444
56.0
ModeResult(mode=array([34]), count=array([2]))


In [ ]:
'''''''''''''''''''''''''''''''''''''''THANKYOU'''''''''''''''''''''''''''''''''''''''''''''''